### PR TITLE
Supervisor monopoly view can overlap queue health tooltip

### PR DESCRIPTION
**Pull request by clottman**
Fixes https://admin.crisistextline.org/jira/browse/AT-1929 

Fixed version: 
image

### CODE REVIEW

**Comment by kidatsy** [comment]
This definitely fixes the issue w/ the header within the app - have you checked how it interacts with the login screen overlay? We'll want to make sure that the overlay covers everything on the actual platform. That would also include the blue bar system message, which I've seen floating above the login page when we've had it up on prod, so you might be able to kill both birds with this... stone? You check it out by changing the `app_env` param to anything other than `local`, in your local.

**Comment by clottman** [comment]
It looks normal.

**Review by kidatsy — APPROVED** [review]
LGTM!

**Comment by kidatsy** [comment]
make sure to include a PR on app that includes these changes and the regenerated CSS that includes them, in the `web` dir

**Pull request merged**
